### ISSUE TITLE
How to start and run it

### ISSUE THREAD

**Issue by ghost** [baidu-security/openrasp-testcases#2]
Please share the detailed steps to start and test openrasp-testcases code. Also, how to run the same along with baidu/open-rasp code.

Also, please mention about to set up mysql, run and test

**Comment by CaledoniaProject** [comment]
You may take a look at https://github.com/baidu/openrasp/wiki/Installation

**Comment by CaledoniaProject** [comment]
I've created another wiki https://github.com/baidu-security/openrasp-testcases/wiki/Installation
