### ISSUE TITLE
ssrf重定向的短网址失效了。

### ISSUE THREAD

**Issue by xuing** [baidu-security/openrasp-testcases#30]
RT，原先使用的`http://uee.me/cFas3`，本该指向127.0.0.1的短网址失效了。指向了别的网页。
导致SSRF系列的测试样例无法正常工作，我重新生成了一个。
`http://n5d.net/mbrhm`
不过也是临时之法。或许可以换一个长期有效的302重定向网址。

**Comment by CaledoniaProject** [comment]
已修改
